### ISSUE TITLE
Hash symbol (#) in filename templates interpreted as comment

### ISSUE THREAD

**Issue by aaduszki** [art-framework-suite/fhicl-cpp#12]
**Describe the bug**
In ICARUS, we store our artdaq FHiCL configuration in a DB, which we access using conftool.py. When comparing two versions of our configurations (`Physics_General_Thr400_Majority_5_10_00020` and `Physics_General_Thr400_Majority_5_10_00021`), I discovered the diff output if full of entries like this:
```
32c32
< outputs.testOutputBNB.fileName: '/data/test_daq/data_dl3_fstrmBNB_run%R_%#_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root'
---
> outputs.testOutputBNB.fileName: '/data/test_daq/data_dl3_fstrmBNB_run%R_%#_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root' #_%to.root'
```
It appears to me, that the # symbol which is used in art filename templates is interpreted as a comment and is repeatedly appended at the end of the line in each consecutive version of the configuration.

Our software versions:
```
fhiclcpp          v4_15_03        -f Linux64bit+3.10-2.17 -q e20:prof        -z /daq/software/products
artdaq_database   v1_05_08        -f Linux64bit+3.10-2.17 -q e20:prof:s112   -z /daq/software/products
```

**To Reproduce**
```
mkdir 20 21
cd 21
conftool.py exportConfiguration Physics_General_Thr400_Majority_5_10_00021
cd ../20
conftool.py exportConfiguration Physics_General_Thr400_Majority_5_10_00020
diff Physics_General_Thr400_Majority_5_10_/ ../21/Physics_General_Thr400_Majority_5_10_/
```

**If this is a high-priority issue**
This is not a showstopper, but this makes comparing the configurations very difficult, as the diffs are cluttered with the entries like the one above

**Comment by knoepfel** [comment]
@aaduszki, this appears to be a bug with `conftool.py`, which is not provided by the art suite.  Do you know who provides that utility--i.e. `which conftool.py`?

**Comment by knoepfel** [comment]
Ah, looks like it's provided by https://github.com/art-daq/artdaq_database.  Please log this issue there.  Thanks!

**Comment by aaduszki** [comment]
I see, I wasn't sure. I will create another report there. Thank you!
