### ISSUE TITLE
Configuration database of art/ROOT file missing last job configuration

### ISSUE THREAD

**Issue by PetrilloAtWork** [art-framework-suite/fhicl-cpp#14]
## Bug description

The problem is that processing an ICARUS (data) file with a standard reconstruction configuration ("stage0"), the configuration database of the ROOT output file seems not to list that configuration and process.
`file_info_dumper` correctly reports two processes having happened, but a configuration dump shows only the process in the input file (`DAQEVB04`) and not the one of the job that created the file (`stage0`).

Even stranger, if I cut out either an unused service or a specific module, the `stage0` configuration is instead correctly written. In the past I did not notice this effect, so it may even be due to some changes in art. Or not.

## To Reproduce

In `/exp/icarus/data/users/petrillo/for/art`, accessible from an ICARUS GPVM, there is an input ROOT file and three configurations to show the issue (genially named "good1", "good2" and "broken"). Setup instructions are written on the top of each FHiCL file, and that's just:
    
    source /cvmfs/icarus.opensciencegrid.org/products/icarus/setup_icarus.sh
    setup icaruscode v09_82_01 -q e26:prof
    
I checked the outcome of each using `config_dumper -P -f stage0 test.root`.

### Whether this is a high-priority issue

The priority depends on the nature of the issue: if it's a real, general problem, it should be addressed before ICARUS starts taking "Run3" data (1-2 weeks). If it's only my problem, then the solution schedule is more relaxed.

**Users can't add labels to the issues anyway.**

**Comment by knoepfel** [comment]
The error lies in this portion of `fhicl::ParameterSetRegistry::exportTo`:

```c++
void
fhicl::ParameterSetRegistry::exportTo(sqlite3* db)
{
  ...
  for (auto const& p : instance_().registry_) {
    std::string id(p.first.to_string());
    std::string psBlob(p.second.to_compact_string());  // <== Problem
    ...
  }
  ...
}
```
The call `to_compact_string()` can insert entries into the registry, which leads to undefined behavior when the insertion happens while the registry is already being iterated over.  We are now evaluating solutions to this problem.

**Comment by PetrilloAtWork** [comment]
Thank you Kyle.
Could you clarify:
1. is this old behaviour or something that has introduced "recently" (and when)
2. is the corruption present already in the input file I sent you (that is a raw data file) or does it happen on the second process?

Thank you for the quick investigation, BTW!

**Comment by knoepfel** [comment]
> is this old behaviour or something that has introduced "recently" (and when)

The `fhiclcpp` code has not changed for a long time; it's possible, though, that GCC changed its default hashing parameters for `std::unordered_map` such that we're encountering this error for the first time.

> has the corruption/undefined behaviour already happened in the input file I sent you (that is a raw data file) or does it happen on the second process?

It happens on the second process...not the first.

We believe we have a solution to the problem.  What suites will need to be rebuilt?  art, nutools, and LArSoft?

**Comment by PetrilloAtWork** [comment]
I believe so. If our issue happens when reading the input file (`RootInput`?) then only `art_root_io` is relevant to us.

**Comment by PetrilloAtWork** [comment]
It is not clear to me if artDAQ is also going to be in any way affected.

**Comment by knoepfel** [comment]
Resolved with commit https://github.com/art-framework-suite/fhicl-cpp/commit/b8d2d45a95071f62eb817b4e086e297a4f9a12e8.

**Comment by PetrilloAtWork** [comment]
Hmm... there is code in `lardata` ([`detinfo::DetectorClocksServiceStandard`](https://github.com/LArSoft/lardata/blob/1e271b111ef1905c8f92c34bcc07b9f32bfaab90/lardata/DetectorInfoServices/DetectorClocksServiceStandard.cc#L101-L111) and [`DetectorPropertiesServiceStandard`](https://github.com/LArSoft/lardata/blob/1e271b111ef1905c8f92c34bcc07b9f32bfaab90/lardata/DetectorInfoServices/DetectorPropertiesServiceStandard.cc#L81-L114)) that also access the configuration bypassing _art_. I would appreciate if you could take a fresh look at those and say if they present issues.

**Comment by knoepfel** [comment]
@PetrilloAtWork, that code is not affected by our change—so far the only manifestation of the bug is that some output files may have incomplete configuration information.  Reading what configuration information is available is not affected.

**Comment by knoepfel** [comment]
@PetrilloAtWork, what is your timeline for needing this fix?

**Comment by PetrilloAtWork** [comment]
If I take the statement:
> some output files may have incomplete configuration information
I understand that the issue does affect the data in the files, and that it is not easily predictable when that could happen and how to prevent it.
If this is the case, we don't want to produce data files with this bug hovering on us, and with the beam coming in days I consider the fix critical.
It is understood that the "may have" means everything could go just well, but we should be ready for the worst.

**Comment by knoepfel** [comment]
@PetrilloAtWork, we have already creating art 3.12.01, which includes this fix.  The time it will take for that to propagate through the LArSoft builds is uncertain.  But the SciSoft team is aware of the issue and working on it.  If other art versions need to be addressed, please let us know ASAP.

**Comment by knoepfel** [comment]
@PetrilloAtWork, there is a new release of LArSoft that includes this fix: https://github.com/LArSoft/larsoft/releases/tag/v09_84_00

Please let us know if you encounter any more issues.
